"""Context assembler — loads only what the route needs based on intent.

When a conversation has a stored summary (generated by the summarization
service for long conversations), the assembler injects the summary text
and loads only the most recent messages.  This keeps the token budget
focused on *current* context while preserving the full relationship
history in condensed form.
"""
import logging
import re
from uuid import UUID

from app.db.connection import get_db_connection
from app.models.schemas import (
    NormalizedEvent, Contact, AgentConfig, IntentClassification,
    AssembledContext, Listing, Trigger, Message,
)
from app.tools.listings import get_listing, search_listings

logger = logging.getLogger(__name__)

TOKEN_BUDGET = 8000
TOKENS_PER_MESSAGE = 50  # rough estimate
RECENT_MESSAGES_WITH_SUMMARY = 15  # when a summary exists, load only this many recent msgs


def assemble_context(
    event: NormalizedEvent,
    contact: Contact | None,
    intent: IntentClassification,
    agent: AgentConfig,
) -> AssembledContext:
    """Load the right context based on intent classification."""
    listings: list[Listing] = []
    triggers: list[Trigger] = []
    conversation_history: list[Message] = []
    calendar_slots: list[dict] | None = None
    conversation_summary: str | None = None

    # Load conversation history for known contacts
    if contact:
        conversation_summary, conversation_history = _load_history_with_summary(
            agent.id, contact.id
        )

    # Intent-specific loading
    if intent.intent == "listing_qa":
        listing = _find_referenced_listing(event.body, agent.id)
        if listing:
            listings = [listing]

    elif intent.intent == "scheduling":
        if contact:
            listings = _load_relevant_listings(agent.id, contact)
        calendar_slots = _load_calendar_placeholder(agent.id)
        if contact:
            triggers = _load_contact_triggers(agent.id, contact.id)

    elif intent.intent == "lead_qualification":
        listings = search_listings(agent.id, filters={"status": "active"})

    elif intent.intent == "transaction":
        if contact:
            triggers = _load_contact_triggers(agent.id, contact.id)

    elif intent.intent == "escalation":
        pass  # Just conversation history (already loaded)

    elif intent.intent == "agent_command":
        listings = search_listings(agent.id, filters={"status": "active"})
        calendar_slots = _load_calendar_placeholder(agent.id)

    # Token budget trimming
    summary_tokens = _estimate_summary_tokens(conversation_summary)
    total_tokens = (
        _estimate_tokens(listings, conversation_history, triggers) + summary_tokens
    )
    if total_tokens > TOKEN_BUDGET:
        # Trim conversation history first
        while conversation_history and total_tokens > TOKEN_BUDGET:
            conversation_history.pop(0)
            total_tokens -= TOKENS_PER_MESSAGE
        # Then trim listings if still over
        while len(listings) > 3 and total_tokens > TOKEN_BUDGET:
            listings.pop()
            total_tokens -= 200
        # Last resort: drop summary if still over (fall back to recent-only)
        if total_tokens > TOKEN_BUDGET and conversation_summary:
            conversation_summary = None
            total_tokens -= summary_tokens

    return AssembledContext(
        agent=agent,
        contact=contact,
        listings=listings,
        calendar_slots=calendar_slots,
        triggers=triggers,
        conversation_history=conversation_history,
        conversation_summary=conversation_summary,
        intent=intent,
    )


def _load_history_with_summary(
    agent_id: UUID, contact_id: UUID
) -> tuple[str | None, list[Message]]:
    """Load conversation summary (if any) + recent messages.

    Returns (summary_text | None, recent_messages).
    If a summary exists, loads fewer recent messages to leave budget room.
    Falls back to the original behavior on any error.
    """
    summary_text: str | None = None

    try:
        from app.services.summarization_service import get_conversation_summary

        summary = get_conversation_summary(agent_id, contact_id)
        if summary:
            summary_text = summary.summary_text
    except Exception as e:
        logger.debug(f"Summary lookup skipped: {e}")

    # Decide how many recent messages to load
    limit = RECENT_MESSAGES_WITH_SUMMARY if summary_text else 20
    messages = _load_conversation_history(agent_id, contact_id, limit=limit)

    return summary_text, messages


def _load_conversation_history(
    agent_id: UUID, contact_id: UUID, limit: int = 20
) -> list[Message]:
    """Load the last N messages for a contact."""
    try:
        with get_db_connection() as conn:
            rows = conn.execute(
                """SELECT m.* FROM messages m
                   JOIN conversations c ON m.conversation_id = c.id
                   WHERE c.agent_id = %s AND c.contact_id = %s
                   ORDER BY m.created_at DESC LIMIT %s""",
                [str(agent_id), str(contact_id), limit],
            ).fetchall()
        return [Message(**r) for r in reversed(rows)]
    except Exception as e:
        logger.error(f"Failed to load conversation history: {e}")
        return []


_ADDRESS_STOP_WORDS = frozenset({
    "the", "and", "for", "are", "but", "not", "you", "all", "can", "had",
    "her", "was", "one", "our", "out", "has", "have", "been", "this", "that",
    "with", "from", "about", "what", "when", "how", "any", "some", "there",
    "which", "their", "them", "then", "will", "would", "could", "should",
    "info", "more", "please", "tell", "show", "details", "listing", "house",
    "home", "property", "address", "place", "street", "road", "lane", "drive",
    "avenue", "court", "way", "unit", "apt", "bed", "bath",
})


def _extract_address_tokens(body: str) -> list[str]:
    """Extract plausible address tokens from a message body.

    Returns words/numbers that are likely part of a street address,
    filtering out common conversational stop words and short fragments.
    """
    words = re.findall(r"[a-zA-Z0-9]+", body)
    tokens = []
    for w in words:
        if len(w) <= 2:
            continue
        if w.lower() in _ADDRESS_STOP_WORDS:
            continue
        tokens.append(w)
    return tokens


def _find_referenced_listing(body: str, agent_id: UUID) -> Listing | None:
    """Try to find a listing referenced in the message body.

    Uses a SQL ILIKE query to search for address matches server-side
    instead of loading all listings into memory.
    """
    tokens = _extract_address_tokens(body)
    if not tokens:
        return None

    # Build ILIKE conditions — any token matching the address column
    conditions = ["agent_id = %s", "status = 'active'"]
    params: list = [str(agent_id)]

    ilike_clauses = []
    for token in tokens:
        ilike_clauses.append("address ILIKE %s")
        params.append(f"%{token}%")

    if not ilike_clauses:
        return None

    conditions.append(f"({' OR '.join(ilike_clauses)})")
    where = " AND ".join(conditions)

    try:
        with get_db_connection() as conn:
            rows = conn.execute(
                f"SELECT * FROM listings WHERE {where} LIMIT 5",
                params,
            ).fetchall()
    except Exception as e:
        logger.error(f"Failed to search listings by address: {e}")
        return None

    if not rows:
        return None

    # Score candidates by number of matching tokens and return best match
    candidates = [Listing(**r) for r in rows]
    body_lower = body.lower()
    best: Listing | None = None
    best_score = 0
    for listing in candidates:
        addr_parts = listing.address.lower().split()
        score = sum(1 for part in addr_parts if len(part) > 2 and part in body_lower)
        if score > best_score:
            best_score = score
            best = listing

    return best


def _load_relevant_listings(agent_id: UUID, contact: Contact) -> list[Listing]:
    """Load listings relevant to a contact's preferences."""
    return search_listings(agent_id, filters={"status": "active"})


def _load_contact_triggers(agent_id: UUID, contact_id: UUID) -> list[Trigger]:
    """Load active triggers for a contact."""
    try:
        with get_db_connection() as conn:
            rows = conn.execute(
                """SELECT * FROM triggers
                   WHERE agent_id = %s AND entity_id = %s AND status = 'pending'
                   ORDER BY scheduled_at LIMIT 10""",
                [str(agent_id), str(contact_id)],
            ).fetchall()
        return [Trigger(**r) for r in rows]
    except Exception as e:
        logger.error(f"Failed to load triggers: {e}")
        return []


def _load_calendar_placeholder(agent_id: UUID) -> list[dict]:
    """Placeholder for Google Calendar. Returns empty until Step 18."""
    return []


def _estimate_tokens(
    listings: list[Listing],
    messages: list[Message],
    triggers: list[Trigger],
) -> int:
    """Rough token count estimate."""
    return (
        len(listings) * 200
        + len(messages) * TOKENS_PER_MESSAGE
        + len(triggers) * 50
        + 500  # base system prompt
    )


def _estimate_summary_tokens(summary: str | None) -> int:
    """Estimate tokens for a summary block."""
    if not summary:
        return 0
    # Rough: 1 token per ~0.75 words, plus wrapper overhead
    return max(1, len(summary.split()) * 4 // 3) + 20
